version: '3.9'
x-enviroment: &commonEnvironment
  - VALET_HOME_PATH: ${VALET_HOME_PATH}
  - VALET_STATIC_PREFIX: ${VALET_STATIC_PREFIX}
  - VALET_SERVER_PATH: ${VALET_SERVER_PATH}
  - PATH: /valet/master:$PATH

services: 
  webserver:
    build:
      context: docker/openresty
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    working_dir: ${WORK_DIR_PATH}
    volumes_from: 
      - php
    volumes:
      - ./templates/nginx:/etc/nginx/templates
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD="" 
      - VALET_HOME_PATH=${VALET_HOME_PATH}
      - VALET_STATIC_PREFIX=${VALET_STATIC_PREFIX}
      - VALET_SERVER_PATH=${VALET_SERVER_PATH}
      - PATH=/valet/master:$PATH
    depends_on: 
      - php
      - db
    networks:
      vpc:
        ipv4_address: ${BUTLER_WEBSERVER_IP:-10.172.0.10}
    links:
      - db
    restart: unless-stopped

  php:
    image: jtreminio/php:${BUTLER_PHP_VERSION:-8.0}
    dns:
      - ${BUTLER_DNS_INTERNAL_IP:-10.172.0.101}
    extra_hosts:
      - "host.docker.internal:${BUTLER_GATEWAY:-10.172.0.1}"
    environment: 
      <<: *commonEnvironment
      PHP_INI_SCAN_DIR: ${BUTLER_PHP_MODULES}
      BUTLER_WEBSERVER_IP: ${BUTLER_WEBSERVER_IP:-10.172.0.10}
    working_dir: ${WORK_DIR_PATH}
    volumes:
      - composer:/./composer
      - ./valet:${VALET_PATH}
      - ./.valet-home:${VALET_HOME_PATH}
      - ${DEFAULT_WWW_PATH}:${WORK_DIR_PATH}:rw
    networks:
      vpc:
        ipv4_address: ${BUTLER_PHP_IP:-10.172.0.11}
  
  dns:
    build:
      context: docker/dnsmasq
      dockerfile: Dockerfile
    ports:
      - 53:53/udp
    environment: 
      <<: *commonEnvironment
    volumes:
      - ./templates/dnsmasq:/etc/dnsmasq-templates
    volumes_from: 
      - php
    networks:
      vpc:
        ipv4_address: ${BUTLER_DNS_IP:-10.172.0.100}

  dns-internal:
    image: butler_dns
    ports:
      - 53/udp
    environment: 
      <<: *commonEnvironment
    volumes:
      - ./templates/dnsmasq-internal:/etc/dnsmasq-templates
    volumes_from: 
      - php
    networks:
      vpc:
        ipv4_address: ${BUTLER_DNS_INTERNAL_IP:-10.172.0.101}
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: ""
        MYSQL_USER: "root"
        MYSQL_PASSWORD: ""
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      vpc:
        ipv4_address: ${BUTLER_MYSQL_IP:-10.172.0.12}

volumes:
  composer:

networks:
  vpc:
    driver: bridge
    ipam:
      config:
      - subnet: ${BUTLER_SUBNET:-10.172.0.0/16}
        gateway: ${BUTLER_GATEWAY:-10.172.0.1}
